apiVersion: v1
kind: Service
metadata:
  labels:
    app: proffy-api
  name: proffy-api-service
spec:
  ports:
  - port: 8080
    targetPort: 4000
    nodePort: 31111
  selector:
    app: proffy-api-pod
  type: NodePort